Repository mattermost/mattermost-load-test-ng, pull requests merged in 2023-06, with the labels that each got.

#597 MM-52988: Improve channel name generation logic
  loadtest/control/gencontroller/actions.go
Labels: 4: Reviews Complete

#596 Improve pickRandomKeyFromMap to use generics
  loadtest/store/memstore/random.go
  loadtest/store/memstore/random_test.go
Labels: 4: Reviews Complete

#595 Monitor agents in Pyroscope
  deployment/terraform/metrics.go
  deployment/terraform/strings.go
Labels: 4: Reviews Complete

#542 [MM-47751] MPA: Send Persistent Notifications
  deployment/terraform/strings.go
  docs/load-test-how-to-use.md
  loadtest/control/actions.go
  loadtest/control/simulcontroller/controller.go
  loadtest/store/memstore/store.go
  loadtest/store/memstore/store_test.go
  loadtest/store/store.go
  loadtest/user/user.go
  loadtest/user/userentity/actions.go
Labels: 4: Reviews Complete

#593 MM-50248: Emulate channel member distribution in gencontoller
  api/agent.go
  config/gencontroller.sample.json
  defaults/json.go
  loadtest/control/actions.go
  loadtest/control/gencontroller/actions.go
  loadtest/control/gencontroller/config.go
  loadtest/control/gencontroller/controller.go
  loadtest/control/gencontroller/state.go
  loadtest/control/gencontroller/utils.go
  loadtest/store/memstore/store.go
  loadtest/store/store.go
Labels: 4: Reviews Complete

#589 MM-52856 Inject actions
  Makefile
  api/agent.go
  api/agent_client_test.go
  api/client/agent/agent.go
  api/client/coordinator/coordinator.go
  api/coordinator.go
  api/coordinator_client_test.go
  api/server.go
  cmd/ltctl/loadtest.go
  cmd/ltctl/main.go
  coordinator/cluster/cluster.go
  coordinator/coordinator.go
  deployment/terraform/coordinator.go
  loadtest/control/actions.go
  loadtest/control/clustercontroller/controller.go
  loadtest/control/controller.go
  loadtest/control/gencontroller/controller.go
  loadtest/control/noopcontroller/actions.go
  loadtest/control/noopcontroller/controller.go
  loadtest/control/noopcontroller/controller_test.go
  loadtest/control/simplecontroller/controller.go
  loadtest/control/simulcontroller/actions.go
  loadtest/control/simulcontroller/controller.go
  loadtest/control/simulcontroller/controller_test.go
  loadtest/loadtest.go
Labels: 2: Dev Review

#602 Add a FAQ to clarify how to configure a test to be bounded or unbounded
  docs/faq.md
Labels: 4: Reviews Complete

#600 MM-52704: Limit SSH SG to only current IP
  deployment/terraform/assets/bindata.go
  deployment/terraform/assets/cluster.tf
Labels: 4: Reviews Complete

#604 Reduce number of calls to GetPostsForChannel
  loadtest/control/gencontroller/actions.go
Labels: 4: Reviews Complete

#605 Improve gencontroller global counters handling
  loadtest/control/actions.go
  loadtest/control/gencontroller/actions.go
  loadtest/control/gencontroller/controller.go
  loadtest/control/gencontroller/status.go
  loadtest/control/status.go
  loadtest/loadtest.go
Labels: 4: Reviews Complete

#610 Fix crash in memstore
  loadtest/store/memstore/random.go
Labels: 2: Dev Review

#609 MM-53154: Add getPosts action
  go.mod
  go.sum
  loadtest/control/gencontroller/actions.go
  loadtest/control/gencontroller/controller.go
  loadtest/control/gencontroller/utils.go
Labels: 4: Reviews Complete

#608 MM-53142: Join all teams and track global DMs
  api/agent.go
  loadtest/control/gencontroller/actions.go
  loadtest/control/gencontroller/config.go
  loadtest/control/gencontroller/controller.go
  loadtest/control/gencontroller/state.go
  loadtest/store/memstore/random.go
  loadtest/store/memstore/store.go
  loadtest/store/store.go
Labels: 4: Reviews Complete

#614 Some minor improvements
  loadtest/control/gencontroller/actions.go
  loadtest/control/gencontroller/controller.go
  loadtest/control/gencontroller/state.go
  loadtest/user/userentity/actions.go
Labels: 4: Reviews Complete

#615 Fix init command
  cmd/ltagent/init.go
Labels: 4: Reviews Complete

#618 Fix FAQ entry
  docs/faq.md
Labels: 2: Dev Review

#613 MM-52331: Automate dump ingestion for normal deployments
  cmd/ltctl/main.go
  comparison/deployment.go
  comparison/loadtest.go
  comparison/loadtest_test.go
  config/deployer.sample.json
  deployment/config.go
  deployment/terraform/dump.go
  deployment/utils.go
  docs/deployer_config.md
  loadtest/utils.go
Labels: 3: QA Review
